version: 2.1

executors:
  my-executor:
    docker:
      - image: alpine:3.7

parameters:
  image-tag:
    type: string
    default: "latest"
  workingdir:
    type: string
    default: "~/main"

jobs:
  executor: my-executor
  parameters:
    parameter1:
      type: string
    env_var1:
      type: env_var_name
  steps:
    - run:
        name: my-job commands 1
        command: |
          echo << parameters.parameter1 >>
          echo << parameters.env_var1 >>
          echo << parameters.image-tag >>

workflows:
  my-workflow:
    jobs:
      - my-job:
          parameter1: param1
          env_var1: env1
