version: 2.1

executors:
  my-executor:
    docker:
      - image: alpine:3.7

commands:
  my-command:
    steps:
      - run:
          name: my-command
          command: |
            env

jobs:
  my-job:
    executor: my-executor
    parameters:
      parameter1:
        type: string
      env_var1:
        type: env_var_name
    steps:
      - my-command
      - run:
          name: my-job commands
          command: |
            export checkcheck=true
            echo << parameters.parameter1 >>
            echo << parameters.env_var1 >>
            echo ${<< parameters.parameter1 >>}
            echo ${<< parameters.env_var1 >>}
            echo $parameter1
            echo $env_var1
            echo $checkcheck
      - my-command

workflows:
  my-workflow:
    jobs:
      - my-job:
          parameter1: param1
          env_var1: env1
