version: 2.1

executors:
  my-executor:
    docker:
      - image: alpine:3.7
      
parameters:
  image-tag:
    type: string
    default: "latest"
    
commands:
  print-command:
    parameters:
      para:
        type: string
    steps:
      - run:
        command: echo << parameters.para >>
      
    
jobs:
  my-job:
    executor: my-executor
    parameters:
      parameter1:
        type: string
      env_var1:
        type: env_var_name
    steps:
      - run:
          name: parameters passing
          command: |
            echo << parameters.parameter1 >>
            echo << parameters.env_var1 >>
            echo << pipeline.parameters.image-tag >>
      - print-command:
          para: asdf

workflows:
  my-workflow:
    jobs:
      - my-job:
          parameter1: param1
          env_var1: env1
