# inside config.yml
version: 2.1
jobs:
  myjob:
    parameters:
      preinstall-foo:
        type: string
    machine: true
    steps:
      - run: echo << parameters.preinstall-foo >>
workflows:
  workflow:
    jobs:
      - myjob:
          preinstall-foo: aaa
      - myjob:
          preinstall-foo: bbb
      - myjob:
          preinstall-foo: 
      - myjob
