version: 2.1

executors:
  my-executor:
    docker:
      - image: alpine:3.7

commands:
  my-command:
    steps:
      - run:
          name: my-command
          command: |
            env

jobs:
  my-job:
    executor: my-executor
    parameters:
      parameter1:
        type: string
      env_var1:
        type: env_var_name
    steps:
      - my-command
      - run:
          name: my-job commands 1
          command: |
            export checkcheck=true
            echo << parameters.parameter1 >>
            echo << parameters.env_var1 >>
            echo ${<< parameters.parameter1 >>}
            echo ${<< parameters.env_var1 >>}
            echo $parameter1
            echo $env_var1
            echo $checkcheck
      - my-command
      - run:
          name: my-job commands 2
          command: |
            echo $p1
            echo $e1
            echo $p2
            echo $e2
            echo $p3
            echo $e3
            env
          environment:
            p1: << parameters.parameter1 >>
            e1: << parameters.env_var1 >>
            p2: ${<< parameters.parameter1 >>}
            e2: ${<< parameters.env_var1 >>}
            p3: $parameter1
            e3: $env_var1

workflows:
  my-workflow:
    jobs:
      - my-job:
          parameter1: param1
          env_var1: env1
